/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ws.ModeloGrado;
import ws.WSColegioIntecap;
import ws.WSColegioIntecap_Service;

/**
 *
 * @author Linda
 */
public class vistaGrado extends javax.swing.JFrame implements MouseListener{
DefaultTableModel mimodelGrado;
    ArrayList<ModeloGrado> dataGrado = new ArrayList<>();
    WSColegioIntecap_Service servicio = new WSColegioIntecap_Service();
    WSColegioIntecap cliente = servicio.getWSColegioIntecapPort();
    /**
     * Creates new form vistaGrado
     */
    
    public vistaGrado() {
        initComponents();
         setLocationRelativeTo(null);
        listaAlumnoss();
        tblgrado.addMouseListener(this);
    }
    public void listaAlumnoss(){
        String Titulo[]={"id_grado","nombre_grado"};
        mimodelGrado = new DefaultTableModel(null, Titulo);
        
        dataGrado = (ArrayList<ModeloGrado>) cliente.todosgrados();
        int tamano = cliente.todosgrados().size();
        
        Object[]obj = new Object[3];
        for (int i=0;i<tamano;i++){
            obj[0]=dataGrado.get(i).getIdGrado();
            obj[1]=dataGrado.get(i).getDescripcionGrado();
            
            mimodelGrado.addRow(obj);
        }
        
        tblgrado.setModel(mimodelGrado);
    }
    //accedera a la tabla
  public void vertabla(){
             int numfilas = tblgrado.getColumnCount();
                 
       String[] par = new String[numfilas];
       for( int i =0; i< numfilas; i++){
       par [i]= String .valueOf(tblgrado.getValueAt(tblgrado.getSelectedRow(), i));
 }
 
       String nombregrado = par[1];
       String idgrado = par[0];
       txtgrado.setText(nombregrado);
       txtidgrado.setText(idgrado);


  System.out.println("se esta haciendo click en la tabla");
  }

  public void limpiar(){
      txtidgrado.setText("");
      txtgrado.setText("");
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtgrado = new javax.swing.JTextField();
        btncreargrado = new javax.swing.JButton();
        btneditargrado = new javax.swing.JButton();
        btneliminargrado = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtidgrado = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblgrado = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 255, 204));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("GRADOS");

        jLabel2.setText("Nombre Grado:");

        btncreargrado.setText("crear");
        btncreargrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreargradoActionPerformed(evt);
            }
        });

        btneditargrado.setText("editar");
        btneditargrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditargradoActionPerformed(evt);
            }
        });

        btneliminargrado.setText("eliminar");
        btneliminargrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminargradoActionPerformed(evt);
            }
        });

        jLabel3.setText("ID Grado:");

        btnbuscar.setText("buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btncreargrado)
                        .addGap(18, 18, 18)
                        .addComponent(btneditargrado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btneliminargrado))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtidgrado, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnbuscar))
                            .addComponent(txtgrado, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(85, 85, 85))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtidgrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscar))
                .addGap(1, 1, 1)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtgrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncreargrado)
                    .addComponent(btneditargrado)
                    .addComponent(btneliminargrado))
                .addGap(0, 23, Short.MAX_VALUE))
        );

        tblgrado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblgrado);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncreargradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreargradoActionPerformed
        if(txtgrado.getText().toString().equals("")){
            JOptionPane.showMessageDialog(this, "Ingrese el nombre del grado");
        }else{
        String gradoNuevo = txtgrado.getText().toString();
        ModeloGrado modgrado = new ModeloGrado();
        modgrado.setDescripcionGrado(gradoNuevo);
        cliente.crearGrado(modgrado);
        JOptionPane.showMessageDialog(this, "Se ha añadido exitosamente");
        listaAlumnoss();
        limpiar();
        }
    }//GEN-LAST:event_btncreargradoActionPerformed

    private void btneditargradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditargradoActionPerformed
        if(txtgrado.getText().toString().equals("")||txtidgrado.getText().toString().equals("")){
            JOptionPane.showMessageDialog(this, "Seleccione el grado a editar (id y nombre)");
        }else{
        String gradoEditado = txtgrado.getText().toString();
        int idgrados = Integer.parseInt(txtidgrado.getText().toString());
        ModeloGrado modgrado = new ModeloGrado();
        modgrado.setDescripcionGrado(gradoEditado);
        modgrado.setIdGrado(idgrados);
        cliente.actualizarGrado(modgrado);
        JOptionPane.showMessageDialog(this, "Se ha actualizado exitosamente");
        listaAlumnoss();
        limpiar();
        }
    }//GEN-LAST:event_btneditargradoActionPerformed

    private void btneliminargradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminargradoActionPerformed
       if(txtidgrado.getText().toString().equals("")){
            JOptionPane.showMessageDialog(this, "Ingrese el ID del grado que desea eliminar");
        }else{
        int idgrados = Integer.parseInt(txtidgrado.getText().toString());
       cliente.eliminarGrado(idgrados);
       JOptionPane.showMessageDialog(this, "Se ha eliminado exitosamente");
        listaAlumnoss();
        limpiar();
       }
    }//GEN-LAST:event_btneliminargradoActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        if(txtidgrado.getText().toString().equals("")){
            JOptionPane.showMessageDialog(this, "Debe ingresar un ID para la busqueda de grado");
        }else{
        int id = Integer.parseInt(txtidgrado.getText().toString());

         if(cliente.buscarGrado(id).isEmpty()){
           JOptionPane.showMessageDialog(this, "error, no existe grado");
          
         }else{
            List<ModeloGrado> listaid = cliente.buscarGrado(id);
            
            for(int i=0;i<listaid.size();i++){
                String nombregrado = listaid.get(i).getDescripcionGrado();
                System.out.println("esto es nombre grado for"+nombregrado);
                 txtgrado.setText(nombregrado);
                 
                 
            }
       
         }
        }
    }//GEN-LAST:event_btnbuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaGrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaGrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaGrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaGrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaGrado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncreargrado;
    private javax.swing.JButton btneditargrado;
    private javax.swing.JButton btneliminargrado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblgrado;
    private javax.swing.JTextField txtgrado;
    private javax.swing.JTextField txtidgrado;
    // End of variables declaration//GEN-END:variables


    @Override
    public void mouseClicked(MouseEvent e) {
        if (e.getSource()==tblgrado){
            vertabla();
        }
    }

    @Override
    public void mousePressed(MouseEvent e) {
       }

    @Override
    public void mouseReleased(MouseEvent e) {
         }

    @Override
    public void mouseEntered(MouseEvent e) {
        }

    @Override
    public void mouseExited(MouseEvent e) {
         }
}
